{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zccusan-chaos-toolbox.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zccusan-chaos-toolbox.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
