apiVersion: v1
kind: Pod
metadata:
  name: zc-mirror-fio
  namespace: zccusan
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: storage.zcutils.io/example-client
                operator: In
                values:
                  - "true"
  containers:
    - name: fio
      image: docker.io/robjcaskey/zccusan-storage-test:0.1.6
      imagePullPolicy: IfNotPresent
      command: [fio]
      args:
        - --name=zc-mirror-randrw
        - --filename=/data/fio.bin
        - --size=96Mi
        - --rw=randrw
        - --rwmixread=70
        - --bs=4k
        - --ioengine=libaio
        - --iodepth=16
        - --direct=1
        - --runtime=30
        - --time_based=1
        - --group_reporting=1
        - --unlink=1
        - --output-format=json
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: zc-mirror
