apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zc-remote-ram
  namespace: zccusan-ram-xnode
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: zcfabric
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: zc-remote-ram-client
  namespace: zccusan-ram-xnode
spec:
  nodeSelector:
    zccusan.io/role: block-client
  containers:
    - name: client
      image: public.ecr.aws/docker/library/busybox:1.37
      command: [/bin/sh, -c, "trap : TERM INT; sleep infinity & wait"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: zc-remote-ram
