#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACT_DIR="${1:-}"
INVENTORY="${2:-}"
SSH_USER="${SSH_USER:-ubuntu}"
SSH_KEY="${SSH_KEY:-/home/rob/robsSecretStore/aws/adhocMasterKeypair-20260523-ed25519}"
SSH_WAIT_SECONDS="${SSH_WAIT_SECONDS:-600}"
QUERY_PROBE_SOURCE="${QUERY_PROBE_SOURCE:-$REPO_ROOT/scripts/io-uring-query-probe.c}"

die() {
	echo "ec2-arm64-nightly-deploy: $*" >&2
	exit 1
}

[ -n "$ARTIFACT_DIR" ] && [ -n "$INVENTORY" ] ||
	die "usage: $0 ARTIFACT_DIR INVENTORY_JSON"
[ -d "$ARTIFACT_DIR" ] || die "artifact directory not found: $ARTIFACT_DIR"
[ -r "$INVENTORY" ] || die "inventory not found: $INVENTORY"
[ -r "$ARTIFACT_DIR/nightly.env" ] || die "nightly.env missing from artifact"
[ -r "$ARTIFACT_DIR/COMPLETE" ] || die "artifact is not marked complete"
command -v jq >/dev/null 2>&1 || die "jq is required"
command -v rsync >/dev/null 2>&1 || die "rsync is required"
command -v aarch64-linux-gnu-gcc >/dev/null 2>&1 ||
	die "aarch64-linux-gnu-gcc is required for the direct UAPI probe"
[ -r "$SSH_KEY" ] || die "SSH key not readable: $SSH_KEY"
[ -r "$QUERY_PROBE_SOURCE" ] || die "query probe source not found: $QUERY_PROBE_SOURCE"

# This file is generated by arm64-kernel-nightly-build.sh and contains only
# validated scalar build metadata.
# shellcheck disable=SC1090
source "$ARTIFACT_DIR/nightly.env"
: "${SOURCE_COMMIT:?missing SOURCE_COMMIT}"
: "${BUILD_KEY:?missing BUILD_KEY}"
: "${KERNEL_RELEASE:?missing KERNEL_RELEASE}"
(cd "$ARTIFACT_DIR" && sha256sum -c SHA256SUMS)

mapfile -t node_rows < <(jq -r '.instances[] | [.instance_id, .public_ip, .private_ip] | @tsv' "$INVENTORY")
[ "${#node_rows[@]}" -gt 0 ] || die "inventory contains no instances"
for row in "${node_rows[@]}"; do
	IFS=$'\t' read -r instance_id public_ip private_ip <<< "$row"
	[ -n "$public_ip" ] && [ "$public_ip" != null ] || die "$instance_id has no public management IP"
	[ -n "$private_ip" ] && [ "$private_ip" != null ] || die "$instance_id has no private data IP"
done

ssh_opts=(
	-o BatchMode=yes
	-o ConnectTimeout=8
	-o ServerAliveInterval=15
	-o StrictHostKeyChecking=accept-new
	-i "$SSH_KEY"
)

probe_build_dir="$(mktemp -d)"
trap 'rm -rf "$probe_build_dir"' EXIT
query_probe="$probe_build_dir/io-uring-query-probe"
aarch64-linux-gnu-gcc -O2 -Wall -Wextra -Werror -static \
	"$QUERY_PROBE_SOURCE" -o "$query_probe"

wait_ssh() {
	local host="$1"
	local deadline=$((SECONDS + SSH_WAIT_SECONDS))
	while (( SECONDS < deadline )); do
		if ssh "${ssh_opts[@]}" "$SSH_USER@$host" true >/dev/null 2>&1; then
			return 0
		fi
		sleep 5
	done
	return 1
}

run_remote_probe() {
	local host="$1"
	local log="$2"
	{
		ssh "${ssh_opts[@]}" "$SSH_USER@$host" \
			"bash '$remote_dir/ec2-graviton-kernel-probe.sh'"
		ssh "${ssh_opts[@]}" "$SSH_USER@$host" \
			"'$remote_dir/io-uring-query-probe'"
	} | tee "$log"
}

remote_dir="/var/tmp/zcutils-arm64-nightly/${BUILD_KEY:0:16}"
reboot_hosts=()
node_index=0
for row in "${node_rows[@]}"; do
	node_index=$((node_index + 1))
	IFS=$'\t' read -r instance_id public_ip private_ip <<< "$row"
	echo "node=$node_index instance=$instance_id management_ip=$public_ip data_ip=$private_ip"
	wait_ssh "$public_ip" || die "SSH did not become ready on $instance_id ($public_ip)"
	ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" "mkdir -p '$remote_dir'"
	rsync -a -e "ssh ${ssh_opts[*]}" \
		"$ARTIFACT_DIR"/*.deb \
		"$ARTIFACT_DIR"/config-* \
		"$ARTIFACT_DIR"/SHA256SUMS \
		"$ARTIFACT_DIR"/COMPLETE \
		"$ARTIFACT_DIR"/nightly.env \
		"$ARTIFACT_DIR"/manifest-*.txt \
		"$REPO_ROOT/scripts/ec2-graviton-kernel-deploy.sh" \
		"$REPO_ROOT/scripts/ec2-graviton-kernel-probe.sh" \
		"$query_probe" \
		"$SSH_USER@$public_ip:$remote_dir/"
	running="$(ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" uname -r)"
	remote_build_key="$(ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" \
		"sudo sed -n 's/^BUILD_KEY=//p' /var/lib/zcutils-graviton-kernel/nightly.env 2>/dev/null || true")"
	if [ "$running" = "$KERNEL_RELEASE" ] && [ "$remote_build_key" = "$BUILD_KEY" ]; then
		echo "node=$node_index action=already-running kernel=$running"
		run_remote_probe "$public_ip" "$ARTIFACT_DIR/probe-node${node_index}.log"
		continue
	fi

	ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" \
		"cd '$remote_dir' && sha256sum -c SHA256SUMS && STAGE_ONE_SHOT=1 bash ./ec2-graviton-kernel-deploy.sh '$remote_dir' && sudo install -m 0644 nightly.env /var/lib/zcutils-graviton-kernel/nightly.env"
	reboot_hosts+=("$node_index"$'\t'"$instance_id"$'\t'"$public_ip")
done

for row in "${reboot_hosts[@]}"; do
	IFS=$'\t' read -r node_index instance_id public_ip <<< "$row"
	echo "node=$node_index action=reboot kernel=$KERNEL_RELEASE"
	ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" 'sudo systemctl reboot' >/dev/null 2>&1 || true
done

[ "${#reboot_hosts[@]}" -eq 0 ] || sleep 10
for row in "${reboot_hosts[@]}"; do
	IFS=$'\t' read -r node_index instance_id public_ip <<< "$row"
	wait_ssh "$public_ip" || die "SSH did not return after reboot on $instance_id ($public_ip)"
	running="$(ssh "${ssh_opts[@]}" "$SSH_USER@$public_ip" uname -r)"
	[ "$running" = "$KERNEL_RELEASE" ] ||
		die "$instance_id booted $running, expected $KERNEL_RELEASE"
	run_remote_probe "$public_ip" "$ARTIFACT_DIR/probe-node${node_index}.log"
	echo "node=$node_index action=verified kernel=$running"
done
