{{- if .Values.installation.enabled }}
{{- $installationId := include "zcblock-csi.installationId" . | trim }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zcblock-csi.installationSecretName" . }}
  namespace: {{ include "zcblock-csi.namespace" . }}
  labels:
    {{- include "zcblock-csi.labels" . | nindent 4 }}
type: Opaque
data:
  ZCCUSAN_INSTALLATION_ID: {{ $installationId | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zcblock-csi.installationConfigMapName" . }}
  namespace: {{ include "zcblock-csi.namespace" . }}
  labels:
    {{- include "zcblock-csi.labels" . | nindent 4 }}
data:
  ZCCUSAN_INSTALLATION_ID: {{ $installationId | quote }}
{{- end }}
