# Development community-survey API profile.
telemetry:
  apiEndpoint: ""

telemetryServer:
  enabled: true

communitySurvey:
  enabled: true
  apiEndpoint: "https://g94w93q6w7.execute-api.us-east-1.amazonaws.com/survey"
